"""Hydrogen Miner Neuron (Final clean version).

Now properly inherits from hydrogen.base.miner.BaseMinerNeuron
following the official Bittensor subnet template structure.
"""

import time
import typing
import bittensor as bt

from hydrogen.protocol import StrategySynapse
from hydrogen.base.miner import BaseMinerNeuron


class Miner(BaseMinerNeuron):
    """
    Hydrogen Miner implementation.
    """

    def __init__(self, config=None):
        super().__init__(config=config)
        bt.logging.info("Hydrogen Miner initialized.")

    async def forward(self, synapse: StrategySynapse) -> StrategySynapse:
        bt.logging.info(f"Received strategy request for challenge: {synapse.challenge_id}")

        # TODO: Replace with real strategy generation / local validation logic
        if synapse.strategy is None:
            synapse.strategy = {
                "backbone": "PINO",
                "pino": {
                    "loss_vector": {"pde_residual": 1.0, "boundary": 0.8}
                },
            }
            synapse.accepted = True
            synapse.message = "Strategy generated by miner"
        else:
            synapse.accepted = True
            synapse.message = "Strategy submission received"
            synapse.submission_id = f"sub_{int(time.time())}"

        return synapse

    async def blacklist(self, synapse: StrategySynapse) -> typing.Tuple[bool, str]:
        if synapse.dendrite is None or synapse.dendrite.hotkey is None:
            return True, "Missing dendrite/hotkey"

        if synapse.dendrite.hotkey not in self.metagraph.hotkeys:
            return True, "Unrecognized hotkey"

        return False, "Hotkey recognized"

    async def priority(self, synapse: StrategySynapse) -> float:
        if synapse.dendrite is None or synapse.dendrite.hotkey is None:
            return 0.0
        try:
            uid = self.metagraph.hotkeys.index(synapse.dendrite.hotkey)
            return float(self.metagraph.S[uid])
        except Exception:
            return 0.0


if __name__ == "__main__":
    with Miner() as miner:
        while True:
            bt.logging.info("Hydrogen Miner running...")
            time.sleep(10)
